### ISSUE TITLE
Defekt Ubuntu Download

### ISSUE THREAD

**Issue by flofriday** [Moeditor/moeditor.org#1]
I just found your mistake. 
It is just a simply writing mistake. Down are the two links the first one is the one that works (with the mistake (according to older releases)), the second one is the one you used on your website.
### https://github.com/Moeditor/Moeditor/releases/download/v0.1.1-beta/moeditor_0.1.1-1_amd64.deb

Hope you can fix this soon.

**Comment by Menci** [comment]
Sorry, the filename I uploaded is wrong. Now I corrected it in the releases.

Now the download link works.
